service: workshop-${self:custom.name}

frameworkVersion: '3'

custom:
  name: luisserrano
  export-env:
    overwrite: true

  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: false # disable all cache for now, since it has additional costs and is something that should only be enabled at a later time based on usage
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 300 # defaults to the maximum allowed: 3600
    dataEncrypted: true # defaults to false
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning".

  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500

  #  # Disabled WAF Association for now, since WAF is not being created
  #  associateWaf:
  #    name: MyWAFRegionalWebACL
  #    version: Regional #(optional) Regional | V2

  alerts:
    stages:
      - production
      - dev
    dashboards: vertical #true
    topics:
      alarm:
        # https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-serverless-core-variables
        topic: ${self:service}-${sls:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: LMSSerrano@gmail.com
    alarms:
      # Default (although fine-tuned)
      - functionErrors
      - functionThrottles
      - functionInvocations
      - functionDuration
    #      # Custom
    #      - restaurantsSearchErrors
    #      - restaurantsSearchLatency
    definitions:
      # Fine-tuning default alarms
      functionInvocations:
        threshold: 100
        treatMissingData: missing
      functionDuration:
        threshold: 500
        treatMissingData: missing
      # Defining new custom alarms
      restaurantsSearchErrors:
        namespace: 'AWS/Lambda'
        description: '/search 5xx errors'
        metric: Errors
        threshold: 0
        treatMissingData: notBreaching
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
      restaurantsSearchLatency:
        namespace: 'prod-serverless-workshop'
        description: '/search latency'
        metric: latency
        threshold: 500
        treatMissingData: notBreaching
        statistic: Average
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold

provider:
  name: aws
  runtime: nodejs16.x

  stage: dev
  region: eu-west-1

  apiGateway:
    metrics: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:scan
          Resource: !GetAtt RestaurantsTable.Arn
        - Effect: Allow
          Action: execute-api:Invoke
          Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/${sls:stage}/GET/restaurants
        - Effect: Allow
          Action: ssm:GetParameters*
          Resource:
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${sls:stage}/get-restaurants/config
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:service}/${sls:stage}/search-restaurants/config

  environment:
    rest_api_url:
      Fn::Join:
        - ""
        - - https://
          - !Ref ApiGatewayRestApi
          - .execute-api.${aws:region}.amazonaws.com/${sls:stage}
    serviceName: ${self:service}
    stage: ${sls:stage}


functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
          caching:
            enabled: true
            ttlInSeconds: 600 # overrides the global setting for ttlInSeconds
          throttling:
            maxRequestsPerSecond: 2000
            maxConcurrentRequests: 1000
    environment:
      restaurants_api: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}/restaurants
      cognito_user_pool_id: !Ref CognitoUserPool
      cognito_client_id: !Ref WebCognitoUserPoolClient
      cognito_server_client_id: !Ref ServerCognitoUserPoolClient # This is here only for acceptance test purposes

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
          authorizer: aws_iam
          caching:
            enabled: true
    environment:
      restaurants_table: !Ref RestaurantsTable

  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
          caching:
            enabled: true
            cacheKeyParameters:
              - name: integration.request.header.theme
                mappedFrom: method.request.body.theme
          request:
            schemas:
              application/json:
                schema: ${file(./schemas/search-restaurants-schema.json)}
                name: PostSearchRestaurantModel
                description: 'Validation model for Searching Restaurants'
    alarms:
      - name: restaurantsSearchErrors
        enabled: true
      - name: restaurantsSearchLatency
        enabled: true
    environment:
      restaurants_table: !Ref RestaurantsTable

resources:
  # Disabled WAF Creation for costing purposes
  #- ${file(./resources/waf.yml)}

  - Resources:
      RestaurantsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: name
              AttributeType: S
          KeySchema:
            - AttributeName: name
              KeyType: HASH

      CognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
          AliasAttributes:
            - email
          UsernameConfiguration:
            CaseSensitive: false
          AutoVerifiedAttributes:
            - email
          Policies:
            PasswordPolicy:
              MinimumLength: 8
              RequireLowercase: true
              RequireNumbers: true
              RequireUppercase: true
              RequireSymbols: true
          Schema:
            - AttributeDataType: String
              Mutable: true
              Name: given_name
              Required: true
              StringAttributeConstraints:
                MinLength: "1"
            - AttributeDataType: String
              Mutable: true
              Name: family_name
              Required: true
              StringAttributeConstraints:
                MinLength: "1"
            - AttributeDataType: String
              Mutable: true
              Name: email
              Required: true
              StringAttributeConstraints:
                MinLength: "1"

      WebCognitoUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
          ClientName: web
          UserPoolId: !Ref CognitoUserPool
          ExplicitAuthFlows:
            - ALLOW_USER_SRP_AUTH
            - ALLOW_REFRESH_TOKEN_AUTH
          PreventUserExistenceErrors: ENABLED

      ServerCognitoUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
          ClientName: server
          UserPoolId: !Ref CognitoUserPool
          ExplicitAuthFlows:
            - ALLOW_ADMIN_USER_PASSWORD_AUTH
            - ALLOW_REFRESH_TOKEN_AUTH
          PreventUserExistenceErrors: ENABLED

  - Outputs:
      RestaurantsTableName:
        Value: !Ref RestaurantsTable

      CognitoUserPoolId:
        Value: !Ref CognitoUserPool

      CognitoUserPoolArn:
        Value: !GetAtt CognitoUserPool.Arn

      CognitoUserPoolWebClientId:
        Value: !Ref WebCognitoUserPoolClient

      CognitoUserPoolServerClientId:
        Value: !Ref ServerCognitoUserPoolClient

plugins:
  - serverless-export-env
  - serverless-api-gateway-caching
  - serverless-api-gateway-throttling
  - serverless-associate-waf
  - serverless-plugin-aws-alerts
