Resources:
  GetRestaurantsConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:service}/${sls:stage}/get-restaurants/config
      Description: get-restaurants configuration for ${self:service}/${sls:stage}
      Type: String
      Value: |
        {
          "defaultResults": 8
        }
  SearchRestaurantsConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:service}/${sls:stage}/search-restaurants/config
      Description: search-restaurants configuration for ${self:service}/${sls:stage}
      Type: String
      Value: |
        {
          "defaultResults": 8
        }
  KmsArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /${self:service}/${sls:stage}/kmsArn
      Description: kmsArn used for ${self:service}/${sls:stage}
      Type: String
      Value: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/workshop-luisserrano
